# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=250, verbose_name='MODULE NAME')),
                ('resource_name', models.CharField(max_length=250, verbose_name='RESOURCE NAME')),
                ('module_duration', models.CharField(max_length=250, verbose_name='MODULE DURATION')),
                ('client_name', models.CharField(max_length=250, verbose_name='CLIENT NAME')),
            ],
        ),
    ]
